### ISSUE TITLE
Spring Boot App @1 - Updates

### ISSUE THREAD

**Issue by Budlee** [jpgough/api-workshop#11]
Couple of notes on the app for the first part of the app.

* The image to create the app in the spring initialiser show shows 2.1.5 as the release. The current release is 2.1.7
* The eclipse instructions to bring in JUnit show say JUnit5. 2.1.7 currently brings in JUnit 4 by default so I thing it could lead to miss configuration unless this has been tested?

**Comment by jpgough** [comment]
I'll also add docker instructions as part of resolving this issue
