### ISSUE TITLE
Contract Driven Development Feedback

### ISSUE THREAD

**Issue by jpgough** [jpgough/api-workshop#24]
* a Mixture of examples, Pizza/Google. Should we just center on the todo service? I think that will lead nicer into the lab.
* It’s not so clear when we are moving between Spring Cloud Contract and pact. I’m wondering if the flow would work better as Producer driven contracts with diagrams, and the technology. Followed by what’s a consumer driven contract and how does that differ with a diagram.
* Missing conversation on stub server/broker and how that leads to more effective team collaboration

**Comment by Budlee** [comment]
Add a note that the ContractBase should go into the test folder and NOT in main
