### ISSUE TITLE
Add swagger-codegen-cli pre-req to repo 

### ISSUE THREAD

**Issue by nickebbitt** [jpgough/api-workshop#38]
Rather than ask people to download the swagger-codegen-cli as a pre-req, maybe we could just add the JAR to the repo under correct lab? One less step for people to do.

http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.3.1/swagger-codegen-cli-2.3.1.jar

**Comment by jpgough** [comment]
I think we should hold off on this issue for now, the OpenApi codegen team are planning on submitting a PR to add their tool to this lab
