### ISSUE TITLE
API Best Practacies Slides

### ISSUE THREAD

**Issue by Budlee** [jpgough/api-workshop#55]
A new set of slides  should be created that can be used to discuss API Best practacies.

This should have some best practacies from MSFT included. It is important to show that that the key part is to take a standard and follow it. This will give you consistancy

**Comment by jpgough** [comment]
This won't be a new slide deck, but will be integrated as a Gateways and Best Practices slide deck for part 5

**Comment by Budlee** [comment]
Updated the issue
